import assert from 'node:assert/strict'
import { readFile, readdir, writeFile } from 'node:fs/promises'
import { resolve, join } from 'node:path'
import { withWorkspace, openBookCreator, openGeneration } from './browser-workspace.ts'
const output = resolve(process.argv[2])
const mode = process.argv[3] ?? 'workflow'
await withWorkspace(output, async page => {
  const body = page.getByRole('textbox', { name: 'Chapter text', exact: true })
  const panel = page.locator('.sn-facts'), proposals = page.locator('.sn-proposals')
  const saved = () => page.locator('.sn-editor-toolbar [role=status]').filter({ hasText: /^Saved$/ }).waitFor()
  if (mode === 'workflow') {
    await openBookCreator(page)
    await page.getByRole('textbox', { name: 'Book title', exact: true }).fill('证据渡河')
    await page.getByRole('button', { name: 'New book', exact: true }).click()
    await page.getByRole('textbox', { name: 'Chapter title', exact: true }).fill('第一章')
    await page.getByRole('button', { name: 'New chapter', exact: true }).click()
    await body.fill('左腕受伤。雨落在船板上。')
    await page.getByRole('button', { name: 'Save', exact: true }).click(); await saved()
    await page.locator('#sn-tab-references').click()
    await panel.getByRole('button', { name: 'Extract fact candidate', exact: true }).click()
    await panel.getByRole('button', { name: 'Accept facts', exact: true }).waitFor()
    await panel.getByRole('button', { name: 'Accept facts', exact: true }).click()
    await panel.getByText('Chapter facts accepted', { exact: true }).waitFor()
    await panel.getByRole('button', { name: 'Locate source', exact: true }).click()
    assert.equal(await body.evaluate(element => element.selectionEnd - element.selectionStart), 12)
    await page.getByRole('textbox', { name: 'Chapter title', exact: true }).fill('第二章')
    await page.getByRole('button', { name: 'New chapter', exact: true }).click()
    await body.waitFor()
    await page.waitForFunction(() => document.querySelector('input[aria-label="Rename"]')?.value === '第二章' && document.querySelector('textarea[aria-label="Chapter text"]')?.value === '')
    await openGeneration(page)
    await proposals.getByRole('checkbox', { name: 'Use previous chapter facts', exact: true }).check()
    await proposals.getByText(/Fact context complete/).waitFor()
    await proposals.getByRole('textbox', { name: 'Writing instructions', exact: true }).fill('保留受伤约束，写下一章。')
    await proposals.getByRole('button', { name: 'Generate', exact: true }).click()
    await proposals.locator('.sn-candidate-status [role=status]').filter({ hasText: /^Ready for review$/ }).waitFor()
    const [bookId] = (await readdir(join(output, 'workspace/novels'))).filter(name => /^[a-f0-9-]{36}$/.test(name))
    const project = JSON.parse(await readFile(join(output, 'workspace/novels', bookId, 'project.json'), 'utf8'))
    const first = project.chapters.find(item => item.title === '第一章')
    await writeFile(join(output, 'workspace/novels', bookId, 'chapters', `${first.chapterId}.md`), '作者改写了旧章。')
    await page.locator('.sn-toolbar').getByRole('button', { name: 'Refresh', exact: true }).click()
    await openGeneration(page)
    await proposals.getByText(/Previous chapter facts expired/).waitFor()
    await proposals.locator('.sn-candidate-status [role=status]').filter({ hasText: /^Expired$/ }).waitFor()
    assert(await proposals.getByRole('button', { name: 'Accept', exact: true }).isDisabled())
    assert.equal(JSON.parse(await readFile(join(output, 'generation-calls.json'), 'utf8')).length, 2)
  } else {
    await page.locator('.sn-chapters').getByRole('button', { name: /第二章/ }).click()
    await page.waitForFunction(() => document.querySelector('input[aria-label="Rename"]')?.value === '第二章')
    await body.waitFor()
    await openGeneration(page)
    await proposals.getByRole('checkbox', { name: 'Use previous chapter facts', exact: true }).check()
    await proposals.getByText(/Previous chapter facts expired/).waitFor()
    assert.equal(JSON.parse(await readFile(join(output, 'generation-calls.json'), 'utf8')).length, 2)
  }
  await page.getByRole('button', { name: 'Fullscreen', exact: true }).click()
  await page.setViewportSize({ width: 900, height: 800 })
  await proposals.scrollIntoViewIfNeeded()
  await page.screenshot({ path: join(output, 'facts-en-light.png') })
  assert(await page.locator('.super-novel-setup').evaluate(element => element.scrollWidth <= element.clientWidth))
  await page.getByRole('button', { name: 'Exit fullscreen', exact: true }).click()
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.getByRole('button', { name: 'Settings', exact: true }).click()
  await page.getByRole('button', { name: 'Dark', exact: true }).click()
  await page.getByRole('button', { name: 'English', exact: true }).click()
  await page.getByText('中文', { exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: '关闭', exact: true }).click()
  await page.getByRole('button', { name: '全屏', exact: true }).click()
  await page.setViewportSize({ width: 900, height: 800 })
  await proposals.scrollIntoViewIfNeeded()
  await page.screenshot({ path: join(output, 'facts-zh-dark.png') })
  console.log(`PASS ${mode}: facts extracted, adopted and cited; source changes expire context.`)
})
