import assert from 'node:assert/strict'
import { readFile, readdir, mkdir } from 'node:fs/promises'
import { resolve, join } from 'node:path'
import { withWorkspace } from './browser-workspace.ts'
const output = resolve(process.argv[2])
const mode = process.argv[3] ?? 'workflow'
await withWorkspace(output, async page => {
  const body = page.getByRole('textbox', { name: 'Chapter text', exact: true })
  const material = page.getByRole('textbox', { name: 'Material text', exact: true })
  const panel = page.locator('.sn-proposals')
  const saved = () => page.locator('.sn-editor-toolbar [role=status]').filter({ hasText: /^Saved$/ }).waitFor()
  if (mode === 'workflow') {
    await page.getByRole('textbox', { name: 'Book title', exact: true }).fill('场景渡河')
    await page.getByRole('button', { name: 'New book', exact: true }).click()
    await page.getByRole('textbox', { name: 'Chapter title', exact: true }).fill('第一章')
    await page.getByRole('button', { name: 'New chapter', exact: true }).click()
    await body.waitFor()
    await page.getByRole('tab', { name: 'Materials and plans', exact: true }).click()
    await page.getByRole('combobox', { name: 'Material type', exact: true }).selectOption('scene')
    await page.getByRole('combobox', { name: 'Related chapter', exact: true }).selectOption({ label: '第一章' })
    await page.getByRole('textbox', { name: 'Material name', exact: true }).fill('渡口场景')
    await page.getByRole('button', { name: 'Create template', exact: true }).click()
    await material.waitFor()
    assert((await material.inputValue()).includes('Private intent'))
    await material.fill('左腕受伤，不能游泳。目的：渡河。转折：船索断裂。')
    await page.getByRole('button', { name: 'Save', exact: true }).click(); await saved()
    await panel.getByRole('textbox', { name: 'Writing instructions', exact: true }).fill('写完整场景蓝图。')
    await panel.getByRole('button', { name: 'Generate', exact: true }).click()
    await panel.locator('.sn-candidate-status [role=status]').filter({ hasText: /^Ready for review$/ }).waitFor()
    await panel.getByRole('button', { name: 'Accept', exact: true }).click()
    await page.waitForFunction(() => document.querySelector('textarea[aria-label="Material text"]')?.value.includes('候选前句'))
    await page.getByRole('tab', { name: 'Chapters', exact: true }).click()
    await body.waitFor()
    assert.equal(await body.inputValue(), '')
    await page.locator('.sn-work-tabs').getByRole('tab', { name: 'Revisions', exact: true }).click()
    await panel.getByText('Select saved materials', { exact: true }).click()
    await panel.getByRole('checkbox', { name: '渡口场景 · Scene', exact: true }).check()
    await panel.getByRole('textbox', { name: 'Writing instructions', exact: true }).fill('依据已采纳场景起草首章。')
    await panel.getByRole('button', { name: 'Generate', exact: true }).click()
    await panel.locator('.sn-candidate-status [role=status]').filter({ hasText: /^Ready for review$/ }).waitFor()
    await panel.getByRole('button', { name: 'Accept', exact: true }).click()
    await page.waitForFunction(() => document.querySelector('textarea[aria-label="Chapter text"]')?.value.includes('候选前句'))
    const [bookId] = (await readdir(join(output, 'workspace/novels'))).filter(name => /^[a-f0-9-]{36}$/.test(name))
    const book = JSON.parse(await readFile(join(output, 'workspace/novels', bookId, 'project.json'), 'utf8'))
    assert.equal(book.chapters.length, 2)
    assert.equal(book.chapters[1].kind, 'scene')
    assert.equal(book.chapters[1].linkedChapterId, book.chapters[0].chapterId)
    const files = await readdir(join(output, 'workspace/novels', bookId, 'proposals'))
    const proposals = await Promise.all(files.map(name => readFile(join(output, 'workspace/novels', bookId, 'proposals', name), 'utf8').then(JSON.parse)))
    assert.equal(proposals.find(item => item.request.materialIds?.length)?.context[0].kind, 'scene')
    assert.equal(JSON.parse(await readFile(join(output, 'generation-calls.json'), 'utf8')).length, 2)
  } else {
    await body.waitFor()
    assert((await body.inputValue()).includes('候选前句'))
    await page.getByRole('tab', { name: 'Materials and plans', exact: true }).click()
    await page.getByRole('button', { name: /渡口场景 · Scene/ }).click()
    await material.waitFor()
    assert((await material.inputValue()).includes('候选前句'))
    assert.equal(JSON.parse(await readFile(join(output, 'generation-calls.json'), 'utf8')).length, 2)
  }
  await mkdir(join(output, 'screenshots'), { recursive: true })
  await page.getByRole('button', { name: 'Fullscreen', exact: true }).click()
  await page.setViewportSize({ width: 900, height: 800 })
  await panel.scrollIntoViewIfNeeded()
  await page.screenshot({ path: join(output, 'screenshots/materials-en-light.png') })
  assert(await page.locator('.super-novel-setup').evaluate(element => element.scrollWidth <= element.clientWidth))
  await page.getByRole('button', { name: 'Exit fullscreen', exact: true }).click()
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.getByRole('button', { name: 'Settings', exact: true }).click()
  await page.getByRole('button', { name: 'Dark', exact: true }).click()
  await page.getByRole('button', { name: 'English', exact: true }).click()
  await page.getByText('中文', { exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: '关闭', exact: true }).click()
  await page.getByRole('button', { name: '全屏', exact: true }).click()
  await page.setViewportSize({ width: 900, height: 800 })
  await panel.scrollIntoViewIfNeeded()
  await page.screenshot({ path: join(output, 'screenshots/materials-zh-dark.png') })
  console.log(`PASS ${mode}: saved scene planning, candidate adoption and explicit context.`)
})
