/** Packed host history and conflict checks without live model traffic. */
import assert from 'node:assert/strict'
import { readFile, readdir, writeFile, mkdir } from 'node:fs/promises'
import { resolve, join } from 'node:path'
import { pathToFileURL } from 'node:url'
import { randomUUID } from 'node:crypto'
import { openBookCreator, visitPreview, createChapter, openManagement, showContent, waitForFixture, selectBook } from './browser-workspace.ts'
const modulePath = process.env.PLAYWRIGHT_MODULE
if (!modulePath) throw new Error('Provide the installed Playwright module path')
const { chromium } = await import(pathToFileURL(resolve(modulePath)).href)
const output = resolve(process.argv[2])
const mode = process.argv[3] ?? 'workflow'
await waitForFixture(output)
const browser = await chromium.launch({ headless: true })
const errors = []
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } })
  page.setDefaultTimeout(20_000)
  page.on('pageerror', error => errors.push(error.message))
  page.on('dialog', dialog => dialog.accept())
  await page.addInitScript(() => localStorage.setItem('dsh.sessions.current', JSON.stringify({ sessionId: 'super-novel-preview-a' })))
  for (const name of ['Continue', 'Configure later']) await page.addLocatorHandler(page.getByRole('button', { name, exact: true }), button => button.click())
  await visitPreview(page, output)
  await page.getByRole('button', { name: /^(Settings|设置)$/ }).waitFor()
  if (await page.getByRole('button', { name: '设置', exact: true }).isVisible()) {
    await page.getByRole('button', { name: '设置', exact: true }).click()
    await page.getByRole('button', { name: '中文', exact: true }).click()
    await page.getByText('English', { exact: true }).click()
    await page.getByRole('dialog').getByRole('button', { name: 'Close', exact: true }).click()
  }
  const open = async () => {
    const expand = page.getByRole('button', { name: 'Open right sidebar', exact: true })
    const books = page.locator('.sn-books')
    const guide = page.getByText('Novel workspace', { exact: true })
    await books.or(guide).or(expand).first().waitFor()
    if (await expand.isVisible()) await expand.click()
    await books.or(guide).first().waitFor()
    if (!await books.isVisible()) await guide.click()
    await books.waitFor()
  }
  await open()
  const body = page.getByRole('textbox', { name: 'Chapter text', exact: true })
  const saved = () => page.locator('.sn-editor-toolbar [role=status]').filter({ hasText: /^Saved$/ }).waitFor()
  const root = join(output, 'workspace')
  if (mode === 'workflow') {
    await openBookCreator(page)
    await page.getByRole('textbox', { name: 'Book title', exact: true }).fill('历史渡河')
    await page.getByRole('button', { name: 'New book', exact: true }).click()
    await createChapter(page, '第一章')
    const original = '原稿。\n手腕还在疼。'
    await body.fill(original)
    await page.getByRole('button', { name: 'Save', exact: true }).click(); await saved()
    await body.fill('第二稿。')
    await page.getByRole('button', { name: 'Save', exact: true }).click(); await saved()
    const bookId = await page.locator('select[aria-label="Book"]').inputValue()
    await writeFile(join(output, 'history-book-id'), bookId)
    const manifestPath = join(root, 'novels', bookId, 'project.json')
    const project = JSON.parse(await readFile(manifestPath, 'utf8'))
    const chapterId = project.chapters[0].chapterId
    const path = join(root, 'novels', bookId, 'chapters', `${chapterId}.md`)
    await body.fill('本地未保存稿。')
    await writeFile(path, '外部新稿。')
    await openManagement(page)
    await page.locator('.sn-toolbar').getByRole('button', { name: 'Refresh', exact: true }).click()
    await page.getByRole('alert').filter({ hasText: 'The draft baseline changed. Retain both drafts and compare before merging.' }).waitFor()
    await page.getByRole('button', { name: 'Retain both drafts', exact: true }).click()
    await page.getByLabel('Retained local draft', { exact: true }).waitFor()
    assert.equal(await page.getByLabel('Retained local draft', { exact: true }).textContent(), '本地未保存稿。')
    assert.equal(await page.getByLabel('Retained disk draft', { exact: true }).textContent(), '外部新稿。')
    await page.getByRole('textbox', { name: 'Merged text', exact: true }).fill('外部新稿。\n本地未保存稿。')
    await page.getByRole('button', { name: 'Save merged draft', exact: true }).click(); await showContent(page); await saved()
    assert.equal(await readFile(path, 'utf8'), '外部新稿。\n本地未保存稿。')
    await openManagement(page)
    await page.getByText('Chapter history and recovery', { exact: true }).click()
    await page.getByRole('combobox', { name: 'Saved version', exact: true }).selectOption({ label: 'Revision 2 · Save' })
    assert.equal(await page.getByLabel('Historical text', { exact: true }).textContent(), original)
    await page.getByRole('button', { name: 'Restore as new revision', exact: true }).click(); await showContent(page); await saved()
    await page.waitForFunction(expected => document.querySelector('textarea[aria-label="Chapter text"]')?.value === expected, original)
    assert.equal(await readFile(path, 'utf8'), original)
    const { BookStore } = await import(pathToFileURL(join(output, 'home/profiles/web/node_modules/dsh-super-novel/lib/host/book-store.js')).href)
    const broken = await BookStore.at(root, { afterStage: async stage => { if (stage === 'chapter') throw new Error('fixture interruption') } })
    const current = await broken.readChapter(bookId, chapterId)
    await assert.rejects(broken.mutate({ operationId: randomUUID(), bookId, chapterId, expectedRevision: current.book.revision,
      action: 'save', title: '', beforeChapterId: '', content: '计划保存稿。', expectedHash: current.hash }, new AbortController().signal))
    await writeFile(path, '中断后作者新稿。')
    await openManagement(page)
    await page.locator('.sn-toolbar').getByRole('button', { name: 'Refresh', exact: true }).click()
    await page.getByRole('button', { name: 'Recover interrupted save', exact: true }).click()
    await page.getByText('Recovery found new external content. Files and journals were retained. Back up before resolving.', { exact: true }).waitFor()
    await page.getByText('Interrupted save drafts', { exact: true }).click()
    await page.getByRole('button', { name: 'Review recovery drafts', exact: true }).click()
    await page.getByRole('textbox', { name: 'Confirmed recovery text', exact: true }).fill('中断后作者新稿。\n计划保存稿。')
    await page.getByRole('button', { name: 'Confirm text and finish recovery', exact: true }).click(); await showContent(page); await saved()
    assert.equal(await readFile(path, 'utf8'), '中断后作者新稿。\n计划保存稿。')
    assert.equal((await readdir(join(root, 'novels', bookId, 'recoveries'))).length, 1)
  } else {
    await selectBook(page, await readFile(join(output, 'history-book-id'), 'utf8'))
    await body.waitFor()
    assert.equal(await body.inputValue(), '中断后作者新稿。\n计划保存稿。')
    await openManagement(page)
    await page.getByText('Chapter history and recovery', { exact: true }).click()
    await page.getByRole('combobox', { name: 'Saved version', exact: true }).waitFor()
    assert.equal(await page.getByRole('combobox', { name: 'Saved version', exact: true }).locator('option').count(), 7)
  }
  await openManagement(page)
  await mkdir(join(output, 'screenshots'), { recursive: true })
  await page.getByRole('button', { name: 'Fullscreen', exact: true }).click()
  await page.setViewportSize({ width: 900, height: 800 })
  await page.locator('.sn-history').first().scrollIntoViewIfNeeded()
  await page.screenshot({ path: join(output, 'screenshots/history-en-light.png') })
  assert(await page.locator('.super-novel-setup').evaluate(element => element.scrollWidth <= element.clientWidth))
  await page.getByRole('button', { name: 'Exit fullscreen', exact: true }).click()
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.getByRole('button', { name: 'Settings', exact: true }).click()
  await page.getByRole('button', { name: 'Dark', exact: true }).click()
  await page.getByRole('button', { name: 'English', exact: true }).click()
  await page.getByText('中文', { exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: '关闭', exact: true }).click()
  await page.getByRole('button', { name: '全屏', exact: true }).click()
  await page.setViewportSize({ width: 900, height: 800 })
  await page.locator('.sn-history').first().scrollIntoViewIfNeeded()
  await page.screenshot({ path: join(output, 'screenshots/history-zh-dark.png') })
  assert.deepEqual(errors, [])
  console.log(`PASS ${mode}: packed history, merge and interrupted-save recovery.`)
} finally { await browser.close() }
