/** Actual packed Host generation workflow through a fixed adapter, without provider traffic. */
import assert from 'node:assert/strict'
import { readFile, readdir, writeFile, mkdir } from 'node:fs/promises'
import { resolve, join } from 'node:path'
import { pathToFileURL } from 'node:url'
import { openBookCreator, showContent, openGeneration, openDocumentOptions, visitPreview, createChapter } from './browser-workspace.ts'
const modulePath = process.env.PLAYWRIGHT_MODULE
if (!modulePath) throw new Error('Provide the installed Playwright module path')
const { chromium } = await import(pathToFileURL(resolve(modulePath)).href)
const output = resolve(process.argv[2])
const mode = process.argv[3] ?? 'workflow'
const browser = await chromium.launch({ headless: true })
const errors = []
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } })
  page.setDefaultTimeout(20_000)
  page.on('pageerror', error => errors.push(error.message))
  await page.addInitScript(() => localStorage.setItem('dsh.sessions.current', JSON.stringify({ sessionId: 'super-novel-preview-a' })))
  for (const name of ['Continue', 'Configure later']) await page.addLocatorHandler(page.getByRole('button', { name, exact: true }), button => button.click())
  await visitPreview(page, output)
  await page.getByRole('button', { name: /^(Settings|设置)$/ }).waitFor()
  if (await page.getByRole('button', { name: '设置', exact: true }).isVisible()) {
    await page.getByRole('button', { name: '设置', exact: true }).click()
    await page.getByRole('button', { name: '中文', exact: true }).click()
    await page.getByText('English', { exact: true }).click()
    await page.getByRole('dialog').getByRole('button', { name: 'Close', exact: true }).click()
  }
  const panel = page.locator('.sn-proposals')
  const open = async () => {
    const expand = page.getByRole('button', { name: 'Open right sidebar', exact: true })
    const books = page.locator('.sn-books')
    const guide = page.getByText('Novel workspace', { exact: true })
    await books.or(guide).or(expand).first().waitFor()
    if (await expand.isVisible()) await expand.click()
    await books.or(guide).first().waitFor()
    if (!await books.isVisible()) await guide.click()
    await books.waitFor()
  }
  await open()
  const body = page.getByRole('textbox', { name: 'Chapter text', exact: true })
  const disk = join(output, 'workspace/novels')
  const ready = () => panel.locator('.sn-candidate-status [role=status]').filter({ hasText: /^Ready for review$/ }).waitFor()
  const generate = async (task, instruction) => {
    await openGeneration(page)
    await panel.getByRole('combobox', { name: 'Writing task', exact: true }).selectOption(task)
    await panel.getByRole('textbox', { name: 'Writing instructions', exact: true }).fill(instruction)
    await panel.getByRole('button', { name: 'Generate', exact: true }).click()
  }
  const saved = () => page.locator('.sn-editor-toolbar [role=status]').filter({ hasText: /^Saved$/ }).waitFor()
  if (mode === 'workflow') {
    await openBookCreator(page)
    await page.getByRole('textbox', { name: 'Book title', exact: true }).fill('渡河提案')
    await page.getByRole('button', { name: 'New book', exact: true }).click()
    await createChapter(page, '第一章')
    await body.waitFor()
    const original = '前文保持。\n\n选中段。\n\n后文保持。'
    await body.fill(original)
    await page.getByRole('button', { name: 'Save', exact: true }).click()
    await saved()
    await generate('draft', '起草渡河开场。')
    await ready()
    const [bookId] = (await readdir(disk)).filter(name => /^[a-f0-9-]{36}$/.test(name))
    const project = JSON.parse(await readFile(join(disk, bookId, 'project.json'), 'utf8'))
    const path = join(disk, bookId, 'chapters', `${project.chapters[0].chapterId}.md`)
    assert.equal(await readFile(path, 'utf8'), original)
    await panel.getByRole('button', { name: 'Changes', exact: true }).click()
    assert.equal(await panel.getByLabel('Original selection', { exact: true }).textContent(), original)
    await panel.getByRole('button', { name: 'Reject', exact: true }).click()
    await panel.locator('.sn-candidate-status [role=status]').filter({ hasText: /^Rejected$/ }).waitFor()
    assert.equal(await readFile(path, 'utf8'), original)
    await generate('continue', '继续渡河。')
    await ready()
    const addition = await panel.getByLabel('Replacement text', { exact: true }).textContent()
    await panel.getByRole('button', { name: 'Accept', exact: true }).click()
    await showContent(page)
    await saved()
    await body.waitFor()
    await page.waitForFunction(expected => document.querySelector('.sn-books textarea[aria-label="Chapter text"]')?.value === expected, original + addition)
    assert.equal(await readFile(path, 'utf8'), original + addition)
    await body.focus()
    await body.evaluate(element => { const start = element.value.indexOf('选中段。'); element.setSelectionRange(start, start) })
    for (let i = 0; i < 4; i++) await body.press('Shift+ArrowRight')
    await generate('rewrite', '只改选中段。')
    await ready()
    await panel.getByRole('button', { name: 'Changes', exact: true }).click()
    assert.equal(await panel.getByLabel('Original selection', { exact: true }).textContent(), '选中段。')
    const replacement = await panel.getByLabel('Replacement text', { exact: true }).textContent()
    const expected = (original + addition).replace('选中段。', replacement)
    await panel.getByRole('button', { name: 'Accept', exact: true }).click()
    await page.waitForFunction(expected => document.querySelector('.sn-books textarea[aria-label="Chapter text"]')?.value === expected, expected)
    assert.equal(await readFile(path, 'utf8'), expected)
    await generate('draft', '生成后制造外部编辑。')
    await ready()
    await writeFile(path, expected + '\n作者外部新稿。')
    await panel.getByRole('button', { name: 'Accept', exact: true }).click()
    await panel.getByRole('alert').waitFor()
    assert.equal(await readFile(path, 'utf8'), expected + '\n作者外部新稿。')
    await openDocumentOptions(page)
    await page.getByRole('button', { name: 'Read disk version', exact: true }).click(); await showContent(page)
    await page.waitForFunction(expected => document.querySelector('textarea[aria-label="Chapter text"]')?.value === expected, expected + '\n作者外部新稿。')
    await body.fill(expected)
    await page.getByRole('button', { name: 'Save', exact: true }).click()
    await saved()
    await generate('draft', '[slow] 停止候选。')
    await panel.getByRole('button', { name: 'Stop', exact: true }).waitFor()
    await page.getByText('super-novel-preview-b', { exact: true }).first().click()
    await open()
    await panel.getByRole('button', { name: 'Stop', exact: true }).click()
    await panel.locator('.sn-candidate-status [role=status]').filter({ hasText: /^Incomplete$/ }).waitFor()
    assert(await panel.getByRole('button', { name: 'Accept', exact: true }).isDisabled())
    assert.equal(await readFile(path, 'utf8'), expected)
    await generate('draft', '[empty] 空输出。')
    await panel.getByText('The model returned no prose.', { exact: true }).waitFor()
    await generate('draft', '[truncated] 截断输出。')
    await panel.getByText('The output was truncated and cannot be accepted as complete.', { exact: true }).waitFor()
    assert(await panel.getByRole('button', { name: 'Accept', exact: true }).isDisabled())
    const calls = JSON.parse(await readFile(join(output, 'generation-calls.json'), 'utf8'))
    assert.equal(calls.length, 7)
    await page.reload()
    await open()
    await page.locator('#sn-tab-revisions').click()
    await panel.getByText('The output was truncated and cannot be accepted as complete.', { exact: true }).waitFor()
    assert.equal(JSON.parse(await readFile(join(output, 'generation-calls.json'), 'utf8')).length, 7)
  } else {
    await page.locator('#sn-tab-revisions').click()
    await panel.getByRole('combobox', { name: 'Candidate history', exact: true }).waitFor()
    assert(await panel.getByRole('button', { name: 'Accept', exact: true }).isDisabled())
    assert.equal((await panel.getByRole('combobox', { name: 'Candidate history', exact: true }).locator('option').count()), 7)
  }
  await mkdir(join(output, 'screenshots'), { recursive: true })
  await page.getByRole('button', { name: 'Fullscreen', exact: true }).click()
  await page.setViewportSize({ width: 900, height: 800 })
  await panel.scrollIntoViewIfNeeded()
  await page.screenshot({ path: join(output, 'screenshots/proposals-en-light.png') })
  assert(await page.locator('.super-novel-setup').evaluate(element => element.scrollWidth <= element.clientWidth))
  await page.getByRole('button', { name: 'Exit fullscreen', exact: true }).click()
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.getByRole('button', { name: 'Settings', exact: true }).click()
  await page.getByRole('button', { name: 'Dark', exact: true }).click()
  await page.getByRole('button', { name: 'English', exact: true }).click()
  await page.getByText('中文', { exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: '关闭', exact: true }).click()
  await page.getByRole('button', { name: '全屏', exact: true }).click()
  await page.setViewportSize({ width: 900, height: 800 })
  await panel.scrollIntoViewIfNeeded()
  await page.screenshot({ path: join(output, 'screenshots/proposals-zh-dark.png') })
  assert.deepEqual(errors, [])
  console.log(`PASS ${mode}: packed Host candidate workflow, no provider traffic or page errors.`)
} finally { await browser.close() }
