import assert from 'node:assert/strict'
import { readFile, readdir, writeFile } from 'node:fs/promises'
import { join, resolve } from 'node:path'
import { pathToFileURL } from 'node:url'
import { openManagement, openBookCreator, createChapter, withWorkspace, showContent } from './browser-workspace.ts'

export async function checkMaterialLibrary(page, output) {
  page.removeAllListeners('dialog'); page.on('dialog', dialog => dialog.accept(dialog.type() === 'prompt' ? '铜钥匙资料' : undefined))
  await openBookCreator(page); await page.getByLabel('Book title', { exact: true }).fill('素材维护演练')
  await page.getByRole('button', { name: 'New book', exact: true }).click()
  await page.waitForFunction(() => document.querySelector('select[aria-label=Book]')?.selectedOptions[0]?.textContent === '素材维护演练')
  await createChapter(page, '原文章')
  const body = page.getByRole('textbox', { name: 'Chapter text', exact: true })
  await body.fill('林舟手里握着一把铜钥匙。'); await page.getByRole('button', { name: 'Save', exact: true }).click()
  await page.locator('.sn-editor-toolbar [role=status]').filter({ hasText: /^Saved$/ }).waitFor()
  const bookId = await body.getAttribute('data-book-id'), chapterId = await body.getAttribute('data-chapter-id')
  await openManagement(page); await page.getByRole('button', { name: 'Material library', exact: true }).click()
  const panel = page.locator('#sn-panel-library')
  await panel.getByRole('button', { name: 'Back up and enable library', exact: true }).click()
  await panel.getByRole('button', { name: 'Back up and enable library', exact: true }).waitFor({ state: 'hidden' })
  assert((await readdir(join(output, 'workspace', '.super-novel-backups', bookId))).some(name => name.endsWith('.tar.gz')))
  await page.keyboard.press('Escape'); await showContent(page)
  await body.click(); await page.keyboard.press('Meta+A'); await page.getByRole('button', { name: 'Save selection as material', exact: true }).click()
  await page.locator('#sn-panel-selection-material').getByLabel('Material name', { exact: true }).fill('铜钥匙资料')
  await page.getByRole('button', { name: 'Save new material', exact: true }).click()
  await panel.waitFor(); await panel.getByLabel('Search name, aliases or content', { exact: true }).fill('铜钥匙')
  await panel.locator('.sn-reference-list button').first().click()
  assert((await panel.locator('.sn-reference-text').innerText()).includes('铜钥匙'))
  await panel.locator('details').filter({ has: page.locator('summary', { hasText: /^Tags, links and status$/ }) }).locator('summary').first().click()
  await panel.getByLabel('Tags (comma separated)', { exact: true }).fill('渡口, 线索')
  await panel.getByLabel('Aliases (comma separated)', { exact: true }).fill('铜钥匙')
  await panel.getByRole('button', { name: 'Favorites', exact: true }).click()
  await panel.getByRole('button', { name: 'Save material details', exact: true }).click()
  await page.waitForFunction(() => [...document.querySelectorAll('.sn-material-library button')].some(button => button.textContent === 'Save material details' && !button.disabled))
  await panel.getByLabel('Material status', { exact: true }).selectOption('trashed')
  await panel.getByRole('button', { name: 'Save material details', exact: true }).click()
  await panel.getByRole('button', { name: 'Restore material', exact: true }).waitFor()
  await panel.getByRole('button', { name: 'Restore material', exact: true }).click()
  await panel.getByRole('button', { name: 'Restore material', exact: true }).waitFor({ state: 'hidden' })
  const manifest = JSON.parse(await readFile(join(output, 'workspace', 'novels', bookId, 'project.json'), 'utf8'))
  assert.equal(manifest.schemaVersion, 2)
  const material = manifest.chapters.find(item => item.kind === 'seed')
  assert.equal(material.sourceEvidence.chapterId, chapterId); assert.deepEqual(material.tags, ['渡口', '线索']); assert.equal(material.favorite, true)
  assert.equal(await readFile(join(output, 'workspace', 'novels', bookId, 'chapters', `${chapterId}.md`), 'utf8'), '林舟手里握着一把铜钥匙。')
  await panel.getByRole('button', { name: 'AI organization candidate', exact: true }).click()
  await page.locator('#sn-panel-revisions').waitFor(); await page.getByRole('button', { name: 'Accept', exact: true }).waitFor()
  await writeFile(join(output, 'library-validation.json'), JSON.stringify({ result: 'PASS', backupBeforeMigration: true, sourceEvidence: true, fulltext: true, tagsFavorite: true, trashRestore: true, aiCandidate: true }, null, 2))
  console.log('PASS material library: backup/migration, source selection, fulltext, tags/favorite, trash/restore and AI candidate.')
}
if (import.meta.url === pathToFileURL(resolve(process.argv[1])).href) await withWorkspace(resolve(process.argv[2]), page => checkMaterialLibrary(page, resolve(process.argv[2])))
