/** Packed-plugin workflow against the isolated Harness, with no model calls. */
import assert from 'node:assert/strict'
import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises'
import { resolve, join } from 'node:path'
import { pathToFileURL } from 'node:url'
import { randomUUID } from 'node:crypto'
const modulePath = process.env.PLAYWRIGHT_MODULE
if (!modulePath) throw new Error('Provide the installed Playwright module path')
const { chromium } = await import(pathToFileURL(resolve(modulePath)).href)
const output = resolve(process.argv[2] ?? '.test-output/preview-v003')
const mode = process.argv[3] ?? 'create'
const browser = await chromium.launch({ headless: true })
const errors = []
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } })
  page.setDefaultTimeout(15_000)
  page.on('pageerror', error => errors.push(error.message))
  await page.addInitScript(() => localStorage.setItem('dsh.sessions.current', JSON.stringify({ sessionId: 'super-novel-preview-a' })))
  for (const name of ['Continue', 'Configure later']) await page.addLocatorHandler(page.getByRole('button', { name, exact: true }), button => button.click())
  await page.goto(await readFile(join(output, 'preview-url'), 'utf8'))
  await page.getByRole('button', { name: /^(Settings|设置)$/ }).waitFor()
  if (await page.getByRole('button', { name: '设置', exact: true }).isVisible()) {
    await page.getByRole('button', { name: '设置', exact: true }).click()
    await page.getByRole('button', { name: '中文', exact: true }).click()
    await page.getByText('English', { exact: true }).click()
    await page.getByRole('dialog').getByRole('button', { name: 'Close', exact: true }).click()
  }
  const openPanel = async () => {
    const expand = page.getByRole('button', { name: 'Open right sidebar', exact: true })
    if (await expand.isVisible()) await expand.click()
    const books = page.locator('.sn-books')
    const guide = page.getByText('Novel workspace', { exact: true })
    await books.or(guide).first().waitFor()
    if (!await books.isVisible()) await guide.click()
    await page.locator('.sn-books').waitFor()
    await page.getByRole('combobox', { name: 'Book', exact: true }).waitFor()
  }
  await openPanel()
  const body = page.getByRole('textbox', { name: 'Chapter text', exact: true })
  const text = '雨落在渡口。\n\n他把受伤的左腕藏进袖口，右手握住船沿。\n'
  if (mode === 'create') {
    await page.getByRole('textbox', { name: 'Book title', exact: true }).fill('雨夜渡河')
    await page.getByRole('button', { name: 'New book', exact: true }).click()
    await page.getByRole('textbox', { name: 'Chapter title', exact: true }).fill('第一章 渡口')
    await page.getByRole('button', { name: 'New chapter', exact: true }).click()
    await body.fill(text)
    await page.getByRole('button', { name: 'Save', exact: true }).click()
    await page.locator('.sn-editor-toolbar [role=status]').filter({ hasText: /^Saved$/ }).waitFor()
    const disk = join(output, 'workspace/novels')
    const names = await readdir(disk)
    const bookId = names.find(name => /^[a-f0-9-]{36}$/.test(name))
    const manifest = JSON.parse(await readFile(join(disk, bookId, 'project.json'), 'utf8'))
    assert.equal(manifest.title, '雨夜渡河')
    assert.equal(await readFile(join(disk, bookId, 'chapters', `${manifest.chapters[0].chapterId}.md`), 'utf8'), text)
    await body.fill(text + '尚未保存的尾句。')
    await page.getByRole('button', { name: 'Close', exact: true }).click()
    await openPanel()
    assert.equal(await body.inputValue(), text + '尚未保存的尾句。')
    await page.getByText('super-novel-preview-b', { exact: true }).first().click()
    await openPanel()
    assert.equal(await body.inputValue(), text + '尚未保存的尾句。')
    await page.getByRole('button', { name: 'Save', exact: true }).click()
    await page.locator('.sn-editor-toolbar [role=status]').filter({ hasText: /^Saved$/ }).waitFor()
    await page.getByRole('textbox', { name: 'Chapter title', exact: true }).fill('第二章 离岸')
    await page.getByRole('button', { name: 'New chapter', exact: true }).click()
    await page.getByRole('button', { name: 'Move up', exact: true }).click()
    await page.getByRole('textbox', { name: 'Rename', exact: true }).fill('第二章 船离岸')
    await page.getByRole('button', { name: 'Rename', exact: true }).click()
    await page.getByRole('button', { name: 'Move down', exact: true }).click()
    await page.getByRole('button', { name: '第一章 渡口' }).click()
    const file = join(disk, bookId, 'chapters', `${manifest.chapters[0].chapterId}.md`)
    const current = await body.inputValue()
    await body.fill(current + '\n保留的本地改动。')
    await writeFile(file, '外部作者修改。\n')
    await page.getByRole('button', { name: 'Save', exact: true }).click()
    await page.getByRole('alert').filter({ hasText: 'disk content or book revision changed' }).waitFor()
    assert.equal(await readFile(file, 'utf8'), '外部作者修改。\n')
    assert((await body.inputValue()).includes('保留的本地改动。'))
    page.once('dialog', dialog => dialog.accept())
    await page.getByRole('button', { name: 'Read disk version', exact: true }).click()
    await page.getByText('External edits detected.', { exact: false }).waitFor()
    await body.fill(text)
    await page.getByRole('button', { name: 'Save', exact: true }).click()
    await page.locator('.sn-editor-toolbar [role=status]').filter({ hasText: /^Saved$/ }).waitFor()
  } else if (mode === 'boundaries') {
    await page.getByRole('button', { name: '第一章 渡口' }).click()
    const longText = '雨水从屋檐落下，船在河面摇晃。\n\n'.repeat(800)
    await body.fill(longText)
    await page.getByRole('button', { name: 'Save', exact: true }).click()
    await page.locator('.sn-editor-toolbar [role=status]').filter({ hasText: /^Saved$/ }).waitFor()
    assert.equal(await body.inputValue(), longText)
    assert(await body.evaluate(element => element.scrollHeight > element.clientHeight))
    await page.getByText('super-novel-preview-readonly', { exact: true }).first().click()
    await openPanel()
    await page.getByText('This session is read-only.', { exact: false }).waitFor()
    assert.equal(await body.inputValue(), longText)
    assert.equal(await body.getAttribute('readonly'), '')
    assert(await page.getByRole('button', { name: 'New book', exact: true }).isDisabled())
    assert(await page.getByRole('button', { name: 'New chapter', exact: true }).isDisabled())
    assert(await page.getByRole('button', { name: 'Save', exact: true }).isDisabled())
    await page.getByText('super-novel-preview-a', { exact: true }).first().click()
    await openPanel()
    await body.fill(text)
    await page.getByRole('button', { name: 'Save', exact: true }).click()
    await page.locator('.sn-editor-toolbar [role=status]').filter({ hasText: /^Saved$/ }).waitFor()
    const { BookStore } = await import(pathToFileURL(join(output, 'home/profiles/web/node_modules/dsh-super-novel/lib/host/book-store.js')).href)
    const workspace = join(output, 'workspace')
    const store = await BookStore.at(workspace)
    const [book] = await store.list()
    const chapterId = book.chapters[0].chapterId
    const chapter = await store.readChapter(book.bookId, chapterId)
    const interrupted = await BookStore.at(workspace, { afterStage: async stage => {
      if (stage === 'chapter') throw new Error('Browser recovery fixture')
    } })
    await assert.rejects(interrupted.mutate({ operationId: randomUUID(), bookId: book.bookId,
      expectedRevision: book.revision, action: 'save', chapterId, title: '', beforeChapterId: '',
      content: text, expectedHash: chapter.hash }, new AbortController().signal), /Browser recovery fixture/)
    await page.getByRole('button', { name: 'Refresh', exact: true }).first().click()
    await page.getByRole('button', { name: 'Recover interrupted save', exact: true }).click()
    await body.waitFor()
    assert.equal(await body.inputValue(), text)
    assert.equal((await store.readBook(book.bookId)).recoveryRequired, false)
  } else {
    await page.getByRole('button', { name: '第一章 渡口' }).click()
    assert.equal(await body.inputValue(), text)
    await page.getByRole('button', { name: 'Preview', exact: true }).click()
    assert.equal(await page.locator('.sn-preview').textContent(), text)
  }
  await mkdir(join(output, 'screenshots'), { recursive: true })
  await page.screenshot({ path: join(output, 'screenshots/books-en-light.png') })
  await page.getByRole('button', { name: 'Settings', exact: true }).click()
  await page.getByRole('button', { name: 'Dark', exact: true }).click()
  await page.getByRole('button', { name: 'English', exact: true }).click()
  await page.getByText('中文', { exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: '关闭', exact: true }).click()
  await page.getByRole('heading', { name: '小说工作台', exact: true }).waitFor()
  await page.getByRole('button', { name: '全屏', exact: true }).click()
  await page.setViewportSize({ width: 900, height: 800 })
  await page.screenshot({ path: join(output, 'screenshots/books-zh-dark.png') })
  assert(await page.locator('.super-novel-setup').evaluate(element => element.scrollWidth <= element.clientWidth))
  assert.deepEqual(errors, [])
  console.log(`PASS ${mode}: packed Host RPC and chapter UI, persistence, local draft retention, version conflict, locale/theme/layout; no page errors.`)
} finally { await browser.close() }
